services:
  resourcemanager:
    image: donghuynh0/hadoop-resourcemanager:hadoop3.2.1-java8
    platform: linux/amd64
    container_name: resourcemanager
    restart: always
    ports:
     - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env