services:
  namenode:
    image: donghuynh0/hadoop-namenode:hadoop3.2.1-java8
    platform: linux/amd64
    container_name: namenode
    restart: always
    network_mode: host   
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
