version: "3"
services:
  historyserver:
    image: donghuynh0/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

volumes:
  hadoop_historyserver: